---
name: TimedPerms
version: 1.1.1
main: de.timmyrs.TimedPerms
author: timmyRS
website: https://github.com/timmyrs/TimedPerms

commands:
  timedperms: {}

permissions:
  timedperms.reload:
    default: 'op'
  timedperms.playerinfo:
    default: 'op'
